import Foundation
import Testing
@testable import Postmortem

/// Fixtures were generated by MetricKit itself (see Tools/), so the parser
/// is tested against Apple's real JSON layout.
func fixture(_ name: String) throws -> Data {
    let url = try #require(Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Fixtures"))
    return try Data(contentsOf: url)
}

@Suite("Diagnostic payloads")
struct DiagnosticPayloadTests {
    @Test func parsesEveryDiagnosticKind() throws {
        let payload = try DiagnosticPayload(json: fixture("diagnostic-payload"))
        #expect(Set(payload.diagnostics.map(\.kind)) == Set(Diagnostic.Kind.allCases))
        #expect(payload.timeStampBegin != nil)
        #expect(payload.timeStampEnd!.timeIntervalSince(payload.timeStampBegin!) == 86_400)
    }

    @Test func crashDetails() throws {
        let payload = try DiagnosticPayload(json: fixture("diagnostic-payload"))
        let crash = try #require(payload.diagnostics.first { $0.kind == .crash })
        let meta = crash.metadata
        #expect(meta.appVersion == "1.2.0")
        #expect(meta.appBuildVersion == "42")
        #expect(meta.versionDescription == "1.2.0 (42)")
        #expect(meta.bundleIdentifier == "com.example.demo")
        #expect(meta.osVersion == "iPhone OS 18.2 (22C152)")
        #expect(meta.deviceType == "iPhone16,1")
        #expect(meta.pid == 1234)
        #expect(meta.isTestFlightApp == true)
        #expect(meta.lowPowerModeEnabled == false)
        #expect(meta.exceptionType == 6)
        #expect(meta.signal == 5)
        #expect(meta.terminationReason == "Namespace SIGNAL, Code 5 Trace/BPT trap: 5")
        #expect(meta.objectiveCException?.exceptionName == "NSRangeException")
        #expect(meta.objectiveCException?.arguments == ["5", "2"])
        #expect(meta.extra.isEmpty, "unmodeled keys: \(meta.extra.keys.sorted())")
        #expect(crash.title == "NSRangeException")
        #expect(crash.summary.contains("index 5 beyond bounds"))
    }

    @Test func stackTrees() throws {
        let payload = try DiagnosticPayload(json: fixture("diagnostic-payload"))
        let crash = try #require(payload.diagnostics.first { $0.kind == .crash })
        let trace = try #require(crash.stackTrace)
        #expect(trace.callStackPerThread)
        #expect(trace.threads.count == 2)
        #expect(trace.attributedThread?.threadAttributed == true)
        let frames = crash.primaryFrames
        #expect(frames.map(\.binaryName) == ["libswiftCore.dylib", "Demo"])
        #expect(frames[0].offsetIntoBinaryTextSegment == 123_456)
        #expect(frames[0].address == 7_000_000_000)
        #expect(frames[1].binaryUUID == UUID(uuidString: "70B89F27-1634-3580-A695-57CDB41D7743"))
        #expect(trace.binaries.map(\.name) == ["Demo", "libswiftCore.dylib", "libsystem_kernel.dylib"])
    }

    @Test func otherKinds() throws {
        let payload = try DiagnosticPayload(json: fixture("diagnostic-payload"))
        func first(_ kind: Diagnostic.Kind) throws -> Diagnostic { try #require(payload.diagnostics.first { $0.kind == kind }) }
        let hang = try first(.hang)
        #expect(hang.metadata.hangDuration?.seconds == 4)
        #expect(hang.hangType == "Main Runloop Hang")
        #expect(hang.title == "Hang 4 s")
        #expect(try first(.cpuException).metadata.totalCPUTime?.seconds == 90)
        #expect(try first(.cpuException).title == "CPU 90 s in 3 min")
        #expect(try first(.diskWriteException).metadata.writesCaused?.bytes == 2_147_483_648)
        #expect(try first(.appLaunch).metadata.launchDuration?.seconds == 2.5)
        #expect(try first(.appLaunch).title == "Launch took 2.5 s")
    }

    @Test func identifiersAreStableAndDistinct() throws {
        let one = try DiagnosticPayload(json: fixture("diagnostic-payload"))
        let two = try DiagnosticPayload(json: fixture("diagnostic-payload"))
        #expect(one.diagnostics.map(\.id) == two.diagnostics.map(\.id))
        #expect(Set(one.diagnostics.map(\.id)).count == one.diagnostics.count)
    }

    @Test func toleratesMissingAndMalformedSections() throws {
        let json = #"{"crashDiagnostics":[{"diagnosticMetaData":{"signal":11,"exceptionType":1,"newKey":"x"},"callStackTree":{"callStacks":[{"callStackRootFrames":[{"address":"0x10","offsetIntoBinaryTextSegment":1e20}]}]}}],"hangDiagnostics":"oops"}"#
        let payload = try DiagnosticPayload(json: Data(json.utf8))
        #expect(payload.diagnostics.count == 1)
        let crash = payload.diagnostics[0]
        #expect(crash.title == "EXC_BAD_ACCESS (SIGSEGV)")
        #expect(crash.metadata.extra["newKey"] == .string("x"))
        #expect(crash.primaryFrames.first?.address == 16)
        #expect(crash.primaryFrames.first?.offsetIntoBinaryTextSegment == nil, "out-of-range values are dropped, not trapped")
        #expect(throws: PostmortemError.self) { try DiagnosticPayload(json: Data("[]".utf8)) }
    }

    @Test func deeplyNestedFramesDontOverflow() throws {
        var frame = #"{"binaryName":"Deep","offsetIntoBinaryTextSegment":1}"#
        for _ in 0..<1000 { frame = #"{"binaryName":"Deep","offsetIntoBinaryTextSegment":1,"subFrames":["# + frame + "]}" }
        let json = #"{"crashDiagnostics":[{"callStackTree":{"callStackPerThread":true,"callStacks":[{"threadAttributed":true,"callStackRootFrames":["# + frame + "]}]}}]}"
        let payload = try DiagnosticPayload(json: Data(json.utf8))
        #expect(payload.diagnostics.first?.primaryFrames.count == 1001, "Foundation's parser stops at 512 levels")
        #expect(throws: (any Error).self) { try JSONSerialization.jsonObject(with: Data(json.utf8)) }
    }

    /// Parsing, comparing, hashing and freeing a stack as deep as
    /// `StackTrace.maximumDepth` on a thread with a small (256 KB) stack, like
    /// the background threads a collector runs on. Recursive teardown of the
    /// tree would overflow it.
    @Test func deepStacksAreSafeOnSmallThreadStacks() async throws {
        var frame = #"{"binaryName":"Deep","offsetIntoBinaryTextSegment":1}"#
        for _ in 0..<StackTrace.maximumDepth { frame = #"{"binaryName":"Deep","offsetIntoBinaryTextSegment":1,"subFrames":["# + frame + "]}" }
        let data = Data((#"{"crashDiagnostics":[{"callStackTree":{"callStackPerThread":true,"callStacks":[{"threadAttributed":true,"callStackRootFrames":["# + frame + "]}]}}]}").utf8)

        let result: Result<Int, any Error> = await withCheckedContinuation { continuation in
            let thread = Thread {
                continuation.resume(returning: Result {
                    let first = try DiagnosticPayload(json: data)
                    let second = try DiagnosticPayload(json: data)
                    #expect(first == second)
                    #expect(first.hashValue == second.hashValue)
                    var edited = second.diagnostics[0].stackTrace!
                    edited.threads[0].rootFrames[0].subFrames[0].binaryName = "Edited"
                    #expect(edited != first.diagnostics[0].stackTrace!)
                    return first.diagnostics[0].primaryFrames.count
                })
            }
            thread.stackSize = 256 * 1024
            thread.start()
        }
        #expect(try result.get() == 2048, "backtraces stop at 2048 frames")
    }
}

@Suite("Crash explanations")
struct CrashExplanationTests {
    func explain(_ fields: [String: JSONValue]) -> CrashExplanation {
        CrashExplanation(DiagnosticMetadata(json: .object(fields)))
    }

    @Test func swiftTrap() {
        let explanation = explain(["exceptionType": .number(6), "signal": .number(5)])
        #expect(explanation.title == "EXC_BREAKPOINT (SIGTRAP)")
        #expect(explanation.summary.contains("force-unwrapping nil"))
    }

    @Test func badAccessIncludesTheRegion() {
        let explanation = explain(["exceptionType": .number(1), "signal": .number(11), "virtualMemoryRegionInfo": .string("0 is not in any region.")])
        #expect(explanation.title == "EXC_BAD_ACCESS (SIGSEGV)")
        #expect(explanation.summary.contains("0 is not in any region"))
    }

    @Test func watchdogTerminations() {
        let explanation = explain(["exceptionType": .number(10), "signal": .number(9), "terminationReason": .string("Namespace FRONTBOARD, Code 0x8badf00d")])
        #expect(explanation.title == "Watchdog Timeout")
        let reason = TerminationReason("Namespace RUNNINGBOARD, Code 0xdead10cc")
        #expect(reason?.namespace == "RUNNINGBOARD")
        #expect(reason?.code == 0xdead10cc)
        #expect(reason?.knownCode?.title == "Held Lock in Background")
        #expect(TerminationReason("Namespace SIGNAL, Code 5 Trace/BPT trap: 5")?.code == 5)
        #expect(TerminationReason("") == nil)
    }

    @Test func unknownCodes() {
        let explanation = explain(["exceptionType": .number(99), "signal": .number(42), "terminationReason": .string("Namespace ODD, Code 0x1")])
        #expect(explanation.title == "EXC_99 (signal 42)")
        #expect(explanation.summary.contains("Namespace ODD"))
    }
}

@Suite("Metric values")
struct MetricValueTests {
    @Test(arguments: [
        ("4 sec", 4.0, "sec"), ("2500 ms", 2500, "ms"), ("2147483648 byte", 2_147_483_648, "byte"),
        ("310000 kB", 310_000, "kB"), ("2,000 ms", 2000, "ms"), ("1,234,567 byte", 1_234_567, "byte"),
        ("4 ms per s", 4, "ms per s"), ("12000000 kiloinstructions", 12_000_000, "kiloinstructions"), ("2,5 sec", 2.5, "sec"),
    ])
    func parses(_ raw: String, _ value: Double, _ unit: String) {
        let parsed = MetricValue(raw)
        #expect(parsed.value == value)
        #expect(parsed.unit == unit)
    }

    @Test func conversions() {
        #expect(MetricValue("2500 ms").seconds == 2.5)
        #expect(MetricValue("3 min").seconds == 180)
        #expect(MetricValue("310000 kB").bytes == 310_000_000)
        #expect(MetricValue("4 ms per s").seconds == nil)
        #expect(MetricValue("garbage").value == nil)
        #expect(MetricValue("").value == nil)
        #expect(MetricValue("250 ms").formatted == "250 ms")
        #expect(MetricValue("90 sec").formatted == "90 s")
        #expect(MetricValue("7200 sec").formatted == "2 h")
        #expect(MetricValue("4 ms per s").formatted == "4 ms per s")
        #expect(MetricValue("1e400 byte").formatted.isEmpty == false, "huge values don't trap")
    }

    @Test func payloadDates() {
        let date = PayloadDate.parse("2026-09-21 09:13:20")
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = .current
        #expect(date.map { calendar.component(.hour, from: $0) } == 9)
        #expect(PayloadDate.parse("not a date") == nil)
        #expect(PayloadDate.parse("2026-09-21T09:13") != nil)
    }
}

@Suite("Metric payloads")
struct MetricPayloadTests {
    @Test func typedMetrics() throws {
        let metrics = try MetricPayload(json: fixture("metric-payload"))
        #expect(metrics.appVersion == "1.2.0")
        #expect(metrics.metadata?.deviceType == "iPhone16,1")
        #expect(metrics.cumulativeCPUTime?.seconds == 250)
        #expect(metrics.peakMemoryUsage?.bytes == 310_000_000)
        #expect(metrics.averageSuspendedMemory?.bytes == 120_000_000)
        #expect(metrics.cumulativeForegroundTime?.seconds == 3600)
        #expect(metrics.cumulativeLogicalWrites?.bytes == 52_000_000)
        #expect(metrics.scrollHitchTimeRatio?.value == 4)
        #expect(metrics.cumulativeWifiDownload?.bytes == 880_000_000)
        #expect(metrics.foregroundExits["cumulativeAppWatchdogExitCount"] == 3)
        #expect(metrics.backgroundExits["cumulativeMemoryPressureExitCount"] == 5)
        #expect(metrics.abnormalExitCount == 3 + 2 + 1 + 5 + 1 + 2)
    }

    @Test func histograms() throws {
        let metrics = try MetricPayload(json: fixture("metric-payload"))
        let launch = try #require(metrics.launchTime)
        #expect(launch.buckets.count == 2)
        #expect(launch.totalCount == 47)
        #expect(launch.buckets[0].start.seconds == 0.3)
        let median = try #require(launch.percentile(0.5))
        #expect(median > 0.3 && median < 0.4)
        let p95 = try #require(launch.percentile(0.95))
        #expect(p95 > 0.4 && p95 <= 0.9)
        #expect(launch.percentile(1) == 0.9)
        #expect(metrics.hangTime?.totalCount == 47)
        #expect(metrics.resumeTime != nil)
        #expect(metrics.optimizedLaunchTime == nil)
        #expect(Histogram(buckets: []).percentile(0.5) == nil)
    }
}

// MARK: - Symbolication

@_cdecl("postmortem_test_marker")
func postmortemTestMarker() -> Int32 { 42 }

@Suite("Symbolication")
struct SymbolicationTests {
    /// Builds a MetricKit-style frame for a live address in this process.
    func frame(for address: UnsafeRawPointer) throws -> StackTrace.Frame {
        var info = Dl_info()
        try #require(dladdr(address, &info) != 0)
        let base = try #require(info.dli_fbase)
        let header = base.assumingMemoryBound(to: mach_header.self)
        let uuid = try #require(Symbolicator.uuid(of: header))
        let offset = UInt64(UInt(bitPattern: address) - UInt(bitPattern: base))
        // MetricKit reports return addresses, which point just past a call.
        return StackTrace.Frame(binaryUUID: uuid, binaryName: String(cString: info.dli_fname).components(separatedBy: "/").last, offsetIntoBinaryTextSegment: offset + 4)
    }

    @Test func resolvesExportedSymbolsInTheTestBinary() throws {
        let function: @convention(c) () -> Int32 = postmortemTestMarker
        let address = try #require(UnsafeRawPointer(bitPattern: unsafeBitCast(function, to: UInt.self)))
        let symbolicated = Symbolicator().symbolicate(try frame(for: address))
        #expect(symbolicated.imageIsLoaded)
        #expect(symbolicated.symbol == "postmortem_test_marker")
        #expect(symbolicated.symbolOffset == 4)
    }

    @Test func resolvesLocalSwiftSymbolsFromTheSymbolTable() throws {
        let closure: @convention(c) (Int32) -> Int32 = { $0 &* 3 &+ 1 }
        let address = try #require(UnsafeRawPointer(bitPattern: unsafeBitCast(closure, to: UInt.self)))
        let symbolicated = Symbolicator().symbolicate(try frame(for: address))
        let symbol = try #require(symbolicated.symbol)
        #expect(symbol.contains("closure"), "\(symbol)")
        #expect(symbol.contains("resolvesLocalSwiftSymbolsFromTheSymbolTable"), "\(symbol)")
    }

    @Test func resolvesSystemLibraries() throws {
        let strlenAddress = try #require(dlsym(UnsafeMutableRawPointer(bitPattern: -2), "strlen"))
        let symbolicated = Symbolicator().symbolicate(try frame(for: strlenAddress))
        #expect(symbolicated.symbol?.hasSuffix("strlen") == true, "\(symbolicated.symbol ?? "nil")")
    }

    @Test func unknownBinariesStayUnresolved() {
        let frame = StackTrace.Frame(binaryUUID: UUID(), binaryName: "Gone", offsetIntoBinaryTextSegment: 100)
        let symbolicated = Symbolicator().symbolicate(frame)
        #expect(!symbolicated.imageIsLoaded)
        #expect(symbolicated.symbol == nil)
        #expect(symbolicated.description == "Gone  +0x64")
        #expect(Symbolicator().symbolicate(StackTrace.Frame()).symbol == nil)
    }

    @Test func demangling() {
        #expect(Demangler.demangle("$sSS") == "Swift.String")
        #expect(Demangler.demangle("_$sSi") == "Swift.Int")
        #expect(Demangler.demangle("_strlen") == "strlen")
        #expect(Demangler.demangle("objc_msgSend") == "objc_msgSend")
    }

    @Test func textReportSymbolicatesLiveFrames() throws {
        let function: @convention(c) () -> Int32 = postmortemTestMarker
        let address = try #require(UnsafeRawPointer(bitPattern: unsafeBitCast(function, to: UInt.self)))
        let liveFrame = try frame(for: address)
        let json = JSONValue.object([
            "diagnosticMetaData": .object(["exceptionType": .number(6), "signal": .number(5), "appVersion": .string("1.0")]),
            "callStackTree": .object([
                "callStackPerThread": .bool(true),
                "callStacks": .array([.object([
                    "threadAttributed": .bool(true),
                    "callStackRootFrames": .array([try JSONValue(encoding: liveFrame)]),
                ])]),
            ]),
        ])
        let payload = try DiagnosticPayload(json: JSONEncoder().encode(JSONValue.object(["crashDiagnostics": .array([json])])))
        let report = DiagnosticReport.text(for: payload.diagnostics[0])
        #expect(report.contains("EXC_BREAKPOINT (SIGTRAP)"))
        #expect(report.contains("postmortem_test_marker + 4"))
        #expect(report.contains("Thread 0 (attributed)"))
    }
}

extension JSONValue {
    init(encoding value: some Encodable) throws {
        self = try JSONDecoder().decode(JSONValue.self, from: JSONEncoder().encode(value))
    }
}

@Suite("Reports")
struct ReportTests {
    @Test func textReportFromFixture() throws {
        let payload = try DiagnosticPayload(json: fixture("diagnostic-payload"))
        let crash = try #require(payload.diagnostics.first { $0.kind == .crash })
        let text = DiagnosticReport.text(for: crash)
        for expected in ["Crash: NSRangeException", "com.example.demo", "1.2.0 (42)", "iPhone16,1 arm64e", "index 5 beyond bounds", "Thread 0 (attributed):", "Binary Images:", "70B89F27-1634-3580-A695-57CDB41D7743  Demo (not loaded)"] {
            #expect(text.contains(expected), "missing \(expected)")
        }
        let hang = try #require(payload.diagnostics.first { $0.kind == .hang })
        #expect(DiagnosticReport.text(for: hang).contains("Samples") == false, "the fixture's hang is per-thread")
    }

    @Test func atosScriptTargetsAppBinaries() throws {
        let payload = try DiagnosticPayload(json: fixture("diagnostic-payload"))
        let crash = try #require(payload.diagnostics.first { $0.kind == .crash })
        let script = DiagnosticReport.atosScript(for: crash)
        #expect(script.contains("UUID=70B89F27-1634-3580-A695-57CDB41D7743"))
        #expect(script.contains("0x100001388"), "0x100000000 + 5000")
        #expect(script.contains("-arch arm64e"))
        #expect(!script.contains("libswiftCore"), "system libraries symbolicate on device")
        let everything = DiagnosticReport.atosScript(for: crash, binaryNames: ["libswiftCore.dylib"])
        #expect(everything.contains("9A0E4C3F-1B6B-3D6E-8A7B-2E3C4D5E6F70"))
    }
}

@Suite("ReportStore")
struct ReportStoreTests {
    func makeStore(maximumCount: Int = 200) -> ReportStore {
        ReportStore(directory: FileManager.default.temporaryDirectory.appending(path: "PostmortemTests-\(UUID().uuidString)"), maximumCount: maximumCount)
    }

    @Test func storesDeduplicatesAndParses() async throws {
        let store = makeStore()
        defer { try? FileManager.default.removeItem(at: store.directory) }
        #expect(try await store.add(fixture("diagnostic-payload"), kind: .diagnostic))
        #expect(try await !store.add(fixture("diagnostic-payload"), kind: .diagnostic), "identical payloads are stored once")
        #expect(try await store.add(fixture("metric-payload"), kind: .metric))
        #expect(try await store.list(.diagnostic).count == 1)
        #expect(try await store.diagnostics().count == 5)
        #expect(try await store.metrics().first?.cumulativeCPUTime?.seconds == 250)
    }

    @Test func rejectsInvalidPayloads() async throws {
        let store = makeStore()
        defer { try? FileManager.default.removeItem(at: store.directory) }
        await #expect(throws: (any Error).self) { try await store.add(Data("nope".utf8), kind: .diagnostic) }
        #expect(try await store.list(.diagnostic).isEmpty)
    }

    @Test func diagnosticsAreDeduplicatedAcrossPayloads() async throws {
        let store = makeStore()
        defer { try? FileManager.default.removeItem(at: store.directory) }
        // The same diagnostics re-delivered inside a payload with a different period.
        var object = try JSONDecoder().decode([String: JSONValue].self, from: fixture("diagnostic-payload"))
        object["timeStampEnd"] = .string("2026-09-23 09:13:20")
        try await store.add(fixture("diagnostic-payload"), kind: .diagnostic)
        try await store.add(JSONEncoder().encode(object), kind: .diagnostic, receivedAt: Date().addingTimeInterval(10))
        #expect(try await store.list(.diagnostic).count == 2)
        #expect(try await store.diagnostics().count == 5)
    }

    @Test func trimsByCountAndAge() async throws {
        let store = makeStore(maximumCount: 2)
        defer { try? FileManager.default.removeItem(at: store.directory) }
        let base = try fixture("metric-payload")
        for index in 0..<4 {
            var object = try JSONDecoder().decode([String: JSONValue].self, from: base)
            object["appVersion"] = .string("1.\(index)")
            try await store.add(JSONEncoder().encode(object), kind: .metric, receivedAt: Date().addingTimeInterval(Double(index)))
        }
        let versions = try await store.metrics().map(\.appVersion)
        #expect(versions == ["1.3", "1.2"], "newest first, oldest trimmed")

        let old = makeStore()
        defer { try? FileManager.default.removeItem(at: old.directory) }
        try await old.add(base, kind: .metric, receivedAt: Date().addingTimeInterval(-100 * 86_400))
        #expect(try await old.list(.metric).isEmpty, "older than 90 days")
    }

    @Test func removalAndChangeNotifications() async throws {
        let store = makeStore()
        defer { try? FileManager.default.removeItem(at: store.directory) }
        var changes = await store.changes().makeAsyncIterator()
        try await store.add(fixture("diagnostic-payload"), kind: .diagnostic)
        #expect(await changes.next() != nil)
        let stored = try #require(try await store.list(.diagnostic).first)
        #expect(try await store.data(for: stored) == fixture("diagnostic-payload"))
        try await store.remove(stored)
        #expect(await changes.next() != nil)
        #expect(try await store.list(.diagnostic).isEmpty)
        try await store.add(fixture("metric-payload"), kind: .metric)
        try await store.removeAll()
        #expect(try await store.list(.metric).isEmpty)
    }
}

@Suite("JSON parser")
struct JSONParserTests {
    @Test func matchesFoundationOnOrdinaryJSON() throws {
        let samples = [
            #"{"a":[1,2.5,-3e2,true,false,null],"b":{"c":"d\n\"é\u00e9\ud83d\ude00"},"e":[],"f":{}}"#,
            #"  [ 1 , { "x" : [ ] } ]  "#,
            #""just a string""#,
            "12",
        ]
        for sample in samples {
            let ours = try JSONParser.parse(Data(sample.utf8))
            let foundation = try JSONDecoder().decode(JSONValue.self, from: Data(sample.utf8))
            #expect(ours == foundation, "\(sample)")
        }
    }

    @Test func rejectsInvalidJSON() {
        for sample in ["", "{", "[1,]", #"{"a" 1}"#, #"{"a":1}x"#, "tru", #""unterminated"#, #"{"a":"\x"}"#, "[1 2]", "-"] {
            #expect(throws: PostmortemError.self, "\(sample)") { try JSONParser.parse(Data(sample.utf8)) }
        }
    }

    @Test func canonicalDataSortsKeysAndRoundTrips() throws {
        let value = try JSONParser.parse(Data(#"{"b":[1,{"z":null,"y":"q\"t"}],"a":true}"#.utf8))
        let canonical = String(decoding: value.canonicalData(), as: UTF8.self)
        #expect(canonical == #"{"a":true,"b":[1,{"y":"q\"t","z":null}]}"#)
        #expect(try JSONParser.parse(value.canonicalData()) == value)
    }

    @Test func fuzzedInputNeverCrashes() throws {
        let base = Array(try fixture("diagnostic-payload"))
        var generator = SystemRandomNumberGenerator()
        for _ in 0..<300 {
            var bytes = base
            for _ in 0..<Int.random(in: 1...8, using: &generator) {
                let position = Int.random(in: 0..<bytes.count, using: &generator)
                switch Int.random(in: 0..<3, using: &generator) {
                case 0: bytes[position] = UInt8.random(in: 0...255, using: &generator)
                case 1: bytes.remove(at: position)
                default: bytes.insert(Array("{}[]\",:0e-".utf8).randomElement(using: &generator)!, at: position)
                }
            }
            _ = try? DiagnosticPayload(json: Data(bytes))
            _ = try? MetricPayload(json: Data(bytes))
        }
    }
}
