import MachO
import Postmortem
import SwiftUI

@main
struct PostmortemDemoApp: App {
    init() {
        // Real apps: start collecting as early as possible.
        PostmortemCollector.shared.start()
    }

    var body: some Scene {
        WindowGroup {
            DemoView()
        }
    }
}

struct DemoView: View {
    private let store = ReportStore.shared

    var body: some View {
        NavigationStack {
            PostmortemView(store: store)
                .toolbar {
                    ToolbarItem(placement: .topBarLeading) {
                        Menu("Samples") {
                            Button("Load Sample Reports") { Task { await loadSamples() } }
                            Button("Load Live Crash") { Task { await loadLiveCrash() } }
                            Divider()
                            Button("Crash Now (force unwrap)", role: .destructive) { crashNow() }
                        }
                        .accessibilityIdentifier("samples")
                    }
                }
        }
        .task {
            if ProcessInfo.processInfo.arguments.contains("-loadSamples") {
                try? await store.removeAll()
                await loadSamples()
                await loadLiveCrash()
            }
        }
    }

    /// Payloads generated by MetricKit itself (see Tools/ in the package).
    func loadSamples() async {
        for (name, kind) in [("diagnostic-payload", StoredPayload.Kind.diagnostic), ("metric-payload", .metric)] {
            guard let url = Bundle.main.url(forResource: name, withExtension: "json", subdirectory: "Fixtures"),
                  let data = try? Data(contentsOf: url) else { continue }
            try? await store.add(data, kind: kind)
        }
    }

    /// A crash whose frames point into this running app and UIKit, so the
    /// viewer can symbolicate it on device.
    func loadLiveCrash() async {
        let frames = LiveSample.frames()
        let json = LiveSample.payload(frames: frames)
        try? await store.add(json, kind: .diagnostic)
    }

    func crashNow() {
        let values: [Int]? = nil
        print(values!.count)
    }
}

@inline(never)
func demoLoadUserProfile() -> Int32 { 7 }

@inline(never)
func demoRefreshLibrary() -> Int32 { 8 }

enum LiveSample {
    /// Frames for real functions: two in this app, one in UIKit.
    static func frames() -> [[String: Any]] {
        let appFunctions: [@convention(c) () -> Int32] = [demoLoadUserProfile, demoRefreshLibrary]
        var addresses = appFunctions.map { UnsafeRawPointer(bitPattern: unsafeBitCast($0, to: UInt.self))! }
        if let uikit = dlsym(UnsafeMutableRawPointer(bitPattern: -2), "UIApplicationMain") {
            addresses.append(UnsafeRawPointer(uikit))
        }
        return addresses.compactMap { address in
            var info = Dl_info()
            guard dladdr(address, &info) != 0, let base = info.dli_fbase else { return nil }
            let header = base.assumingMemoryBound(to: mach_header.self)
            guard let uuid = uuid(of: header) else { return nil }
            return [
                "binaryUUID": uuid.uuidString,
                "binaryName": String(cString: info.dli_fname).components(separatedBy: "/").last ?? "?",
                "offsetIntoBinaryTextSegment": UInt(bitPattern: address) - UInt(bitPattern: base) + 8,
                "address": UInt(bitPattern: address) + 8,
                "sampleCount": 1,
            ]
        }
    }

    static func payload(frames: [[String: Any]]) -> Data {
        var chain: [String: Any]?
        for frame in frames.reversed() {
            var node = frame
            if let chain { node["subFrames"] = [chain] }
            chain = node
        }
        let crash: [String: Any] = [
            "version": "1.0.0",
            "diagnosticMetaData": [
                "appVersion": "1.0", "appBuildVersion": "1", "osVersion": UIDevice.current.systemName + " " + UIDevice.current.systemVersion,
                "deviceType": "Simulator", "exceptionType": 6, "signal": 5, "exceptionCode": 1,
                "terminationReason": "Namespace SIGNAL, Code 5 Trace/BPT trap: 5",
                "bundleIdentifier": Bundle.main.bundleIdentifier ?? "",
            ],
            "callStackTree": ["callStackPerThread": true, "callStacks": [["threadAttributed": true, "callStackRootFrames": [chain ?? [:]]]]],
        ]
        let payload: [String: Any] = ["crashDiagnostics": [crash], "timeStampBegin": "2026-09-26 00:00:00", "timeStampEnd": "2026-09-27 00:00:00"]
        return (try? JSONSerialization.data(withJSONObject: payload)) ?? Data()
    }

    static func uuid(of header: UnsafePointer<mach_header>) -> UUID? {
        var pointer = UnsafeRawPointer(header).advanced(by: MemoryLayout<mach_header_64>.size)
        for _ in 0..<header.pointee.ncmds {
            let command = pointer.assumingMemoryBound(to: load_command.self).pointee
            if command.cmd == UInt32(LC_UUID) {
                return UUID(uuid: pointer.assumingMemoryBound(to: uuid_command.self).pointee.uuid)
            }
            pointer = pointer.advanced(by: Int(command.cmdsize))
        }
        return nil
    }
}
